-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = {
        ["bodyColors"] = {
        ["LowerTorso"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["LeftLowerArm"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["RightUpperArm"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["Head"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["LeftUpperLeg"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["RightHand"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["HumanoidRootPart"] = {
            [1] = 163,
            [2] = 162,
            [3] = 165
        },
        ["UpperTorso"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["LeftUpperArm"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["RightLowerArm"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["LeftHand"] = {
            [1] = 248,
            [2] = 248,
            [3] = 248
        },
        ["LeftFoot"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["RightFoot"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["RightLowerLeg"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["RightUpperLeg"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
        },
        ["LeftLowerLeg"] = {
            [1] = 17,
            [2] = 17,
            [3] = 17
            }
        },
        ["assets"] = {
            [1] = {
                ["id"] = 5028610070,  
                ["tuning"] = {
                    ["scale"] = 1.0477564102564103,
                    ["posz"] = 0.5952380952380953,
                    ["posy"] = -0.10357142857142865,
                    ["usesSimpleColor"] = false,
                    ["rotz"] = 0,
                    ["customTexture"] = "rbxthumb://type=Asset&id=8324276962&w=150&h=150",
                    ["posx"] = 0.023809523809523725,
                    ["s"] = 0,
                    ["version"] = 3,
                    ["textureHidden"] = false,
                    ["v"] = 1,
                    ["shineType"] = 1,
                    ["sz"] = 0.25,
                    ["sy"] = 1,
                    ["rotx"] = 0,
                    ["h"] = 0,
                    ["roty"] = 0,
                    ["sx"] = 1
                }
            },
            [2] = {
                    ["id"] = 439984032, 
                    ["tuning"] = {
                        ["scale"] = 1.1183974358974358,
                        ["posz"] = 0.08095238095238111,
                        ["posy"] = -0.6892857142857143,
                        ["usesSimpleColor"] = false,
                        ["customTexture"] = "rbxthumb://type=Asset&id=8431293666&w=150&h=150",
                        ["rotz"] = 0.01121997376282069,
                        ["posx"] = 0.014285714285714235,
                        ["s"] = 0,
                        ["version"] = 3,
                        ["textureHidden"] = false,
                        ["v"] = 1,
                        ["shineType"] = 1,
                        ["sz"] = 0.4316875,
                        ["sy"] = 1.0111875000000001,
                        ["rotx"] = 0.01121997376282069,
                        ["h"] = 0,
                        ["roty"] = 0.02243994752564138,
                        ["sx"] = 1
                }
            },
            [3] = {
                ["id"] = 6450319986,
                ["tuning"] = {
                    ["scale"] = 1,
                    ["posz"] = 0,
                    ["posy"] = 0,
                    ["usesSimpleColor"] = false,
                    ["rotz"] = 0,
                    ["posx"] = 0,
                    ["s"] = 0,
                    ["textureHidden"] = false,
                    ["v"] = 1,
                    ["shineType"] = 1,
                    ["sz"] = 1,
                    ["sy"] = 1,
                    ["rotx"] = 0,
                    ["h"] = 0,
                    ["roty"] = 0,
                    ["sx"] = 1
                }
            },
            [4] = {
                ["id"] = 32357619,
                ["tuning"] = {
                    ["scale"] = 1,
                    ["posz"] = 0,
                    ["posy"] = 0,
                    ["usesSimpleColor"] = false,
                    ["rotz"] = 0,
                    ["posx"] = 0,
                    ["s"] = 0,
                    ["textureHidden"] = false,
                    ["v"] = 1,
                    ["shineType"] = 1,
                    ["sz"] = 1,
                    ["sy"] = 1,
                    ["rotx"] = 0,
                    ["h"] = 0,
                    ["roty"] = 0,
                    ["sx"] = 1
                }
        },
        [5] = {
            ["id"] = 32357631,
            ["tuning"] = {
                ["scale"] = 1,
                ["posz"] = 0,
                ["posy"] = 0,
                ["usesSimpleColor"] = false,
                ["rotz"] = 0,
                ["posx"] = 0,
                ["s"] = 0,
                ["textureHidden"] = false,
                ["v"] = 1,
                ["shineType"] = 1,
                ["sz"] = 1,
                ["sy"] = 1,
                ["rotx"] = 0,
                ["h"] = 0,
                ["roty"] = 0,
                ["sx"] = 1
            }
    },
    [6] = {
        ["id"] = 32357584,
        ["tuning"] = {
            ["scale"] = 1,
            ["posz"] = 0,
            ["posy"] = 0,
            ["usesSimpleColor"] = false,
            ["rotz"] = 0,
            ["posx"] = 0,
            ["s"] = 0,
            ["textureHidden"] = false,
            ["v"] = 1,
            ["shineType"] = 1,
            ["sz"] = 1,
            ["sy"] = 1,
            ["rotx"] = 0,
            ["h"] = 0,
            ["roty"] = 0,
            ["sx"] = 1
            }
        },
        [7] = {
            ["id"] = 32357663,
            ["tuning"] = {
                ["scale"] = 1,
                ["posz"] = 0,
                ["posy"] = 0,
                ["usesSimpleColor"] = false,
                ["rotz"] = 0,
                ["posx"] = 0,
                ["s"] = 0,
                ["textureHidden"] = false,
                ["v"] = 1,
                ["shineType"] = 1,
                ["sz"] = 1,
                ["sy"] = 1,
                ["rotx"] = 0,
                ["h"] = 0,
                ["roty"] = 0,
                ["sx"] = 1
            }
        },
        [8] = {
            ["id"] = 86499666,
            ["tuning"] = {
                ["scale"] = 1,
                ["posz"] = 0,
                ["posy"] = 0,
                ["usesSimpleColor"] = false,
                ["rotz"] = 0,
                ["posx"] = 0,
                ["s"] = 0,
                ["textureHidden"] = false,
                ["v"] = 1,
                ["shineType"] = 1,
                ["sz"] = 1,
                ["sy"] = 1,
                ["rotx"] = 0,
                ["h"] = 0,
                ["roty"] = 0,
                ["sx"] = 1
            }
        },
        [9] = {
            ["id"] = 5392470876,
            ["tuning"] = {
                ["scale"] = 1,
                ["posz"] = 0,
                ["posy"] = 0,
                ["usesSimpleColor"] = false,
                ["rotz"] = 0,
                ["posx"] = 0,
                ["s"] = 0,
                ["textureHidden"] = false,
                ["v"] = 1,
                ["shineType"] = 1,
                ["sz"] = 1,
                ["sy"] = 1,
                ["rotx"] = 0,
                ["h"] = 0,
                ["roty"] = 0,
                ["sx"] = 1
            }
        },
        [10] = {
            ["id"] = 5392465955,
            ["tuning"] = {
                ["scale"] = 1,
                ["posz"] = 0,
                ["posy"] = 0,
                ["usesSimpleColor"] = false,
                ["rotz"] = 0,
                ["posx"] = 0,
                ["s"] = 0,
                ["textureHidden"] = false,
                ["v"] = 1,
                ["shineType"] = 1,
                ["sz"] = 1,
                ["sy"] = 1,
                ["rotx"] = 0,
                ["h"] = 0,
                ["roty"] = 0,
                ["sx"] = 1
            }
        },
        [11] = {
        ["id"] = 8324276962,
        ["tuning"] = {
            ["scale"] = 1,
            ["posz"] = 0,
            ["posy"] = 0,
            ["usesSimpleColor"] = false,
            ["rotz"] = 0,
            ["posx"] = 0,
            ["s"] = 0,
            ["textureHidden"] = false,
            ["v"] = 1,
            ["shineType"] = 1,
            ["sz"] = 1,
            ["sy"] = 1,
            ["rotx"] = 0,
            ["h"] = 0,
            ["roty"] = 0,
            ["sx"] = 1
        }
    },
    [12] = {
        ["id"] = 134082579,
        ["tuning"] = {
            ["scale"] = 1,
            ["posz"] = 0,
            ["posy"] = 0,
            ["usesSimpleColor"] = false,
            ["customTexture"] = "rbxthumb://type=Asset&id=5855575005&w=150&h=150",
            ["rotz"] = 0,
            ["posx"] = 0,
            ["s"] = 0,
            ["textureHidden"] = false,
            ["v"] = 1,
            ["shineType"] = 1,
            ["sz"] = 1,
            ["sy"] = 1,
            ["rotx"] = 0,
            ["h"] = 0,
            ["roty"] = 0,
            ["sx"] = 1
        }
    },
    [13] = {
        ["id"] = 5028610070, --black 
        ["tuning"] = {
            ["scale"] = 1.0477564102564103,
            ["posz"] = 0.480952380952381,
            ["posy"] = -0.10357142857142865,
            ["usesSimpleColor"] = false,
            ["customTexture"] = "rbxthumb://type=Asset&id=5855575005&w=150&h=150",
            ["rotz"] = 0,
            ["posx"] = 0.023809523809523725,
            ["s"] = 0,
            ["version"] = 3,
            ["textureHidden"] = false,
            ["v"] = 1,
            ["shineType"] = 1,
            ["sz"] = 0.25,
            ["sy"] = 1,
            ["rotx"] = 0,
            ["h"] = 0,
            ["roty"] = 0,
            ["sx"] = 1
}
},
[14] = {
    ["id"] = -105,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[15] = {
    ["id"] = -104,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[16] = {
    ["id"] = -103,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[17] = {
    ["id"] = -102,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[18] = {
    ["id"] = -101,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[19] = {
    ["id"] = -100,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
},
[20] = {
    ["id"] = -99,
    ["tuning"] = {
        ["scale"] = 1,
        ["posz"] = 0,
        ["posy"] = 0,
        ["usesSimpleColor"] = false,
        ["rotz"] = 0,
        ["posx"] = 0,
        ["s"] = 0,
        ["textureHidden"] = false,
        ["v"] = 1,
        ["shineType"] = 1,
        ["sz"] = 1,
        ["sy"] = 1,
        ["rotx"] = 0,
        ["h"] = 0,
        ["roty"] = 0,
        ["sx"] = 1
    }
}
    },
        ["version"] = 12,
        ["scales"] = {
            ["LeftUpperLeg"] = {
                ["y"] = 1.5273453093812372,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            },
            ["LeftLowerArm"] = {
                ["y"] = 1.6111776447105788,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["RightUpperArm"] = {
                ["y"] = 1.5832335329341316,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["Head"] = {
                ["y"] = 1,
                ["x"] = 1,
                ["z"] = 1
            },
            ["RightHand"] = {
                ["y"] = 1.5832335329341316,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["UpperTorso"] = {
                ["y"] = 0.9069860279441118,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["HumanoidRootPart"] = {
                ["y"] = 1,
                ["x"] = 1,
                ["z"] = 1
            },
            ["RightUpperLeg"] = {
                ["y"] = 1.5161676646706586,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            },
            ["LeftUpperArm"] = {
                ["y"] = 1.6111776447105788,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["RightLowerArm"] = {
                ["y"] = 1.5832335329341316,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["LeftHand"] = {
                ["y"] = 1.6111776447105788,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["LowerTorso"] = {
                ["y"] = 0.9069860279441118,
                ["x"] = 0.8852207293666026,
                ["z"] = 0.8852207293666026
            },
            ["LeftFoot"] = {
                ["y"] = 1.5273453093812372,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            },
            ["RightLowerLeg"] = {
                ["y"] = 1.5161676646706586,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            },
            ["RightFoot"] = {
                ["y"] = 1.5161676646706586,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            },
            ["LeftLowerLeg"] = {
                ["y"] = 1.5273453093812372,
                ["x"] = 0.783109404990403,
                ["z"] = 0.783109404990403
            }
        },
        ["id"] = "2F9DADB8-AF14-4124-B9DE-E9B86FE730A7",
        ["username"] = "Sakio",
        ["body"] = "R15"
    },
    [2] = false
}

game:GetService("ReplicatedStorage").Systems.AvatarEditor.Core.Characters.PlayAsPackage:FireServer(unpack(args))


